package demo.entities;
// Generated Apr 6, 2017 8:40:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedbacks generated by hbm2java
 */
@Entity
@Table(name = "feedbacks", catalog = "myProject")
public class Feedbacks implements java.io.Serializable {

	private int id;
	private String subject;
	private String message;
	private String name;
	private String contactNumber;
	private Date receivedDate;

	public Feedbacks() {
	}

	public Feedbacks(int id, String subject, String message, String name, String contactNumber, Date receivedDate) {
		this.id = id;
		this.subject = subject;
		this.message = message;
		this.name = name;
		this.contactNumber = contactNumber;
		this.receivedDate = receivedDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "subject", nullable = false, length = 500)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "message", nullable = false, length = 1000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "contact_number", nullable = false, length = 20)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "received_date", nullable = false, length = 23)
	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

}
