package demo.entities;
// Generated Mar 24, 2017 8:25:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "myProject")
public class Orders implements java.io.Serializable {

	private int id;
	private Accounts accounts;
	private boolean status;
	//@NotEmpty(message = "Please enter your Address.")
	
	private String customerAddress;
	private String customerEmail;
	private String customerName;
	
	private String customerPhone;
	private Date orderDate;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public Orders() {
	}

	public Orders(int id, boolean status, String customerAddress, String customerEmail, String customerName,
			String customerPhone, Date orderDate) {
		this.id = id;
		this.status = status;
		this.customerAddress = customerAddress;
		this.customerEmail = customerEmail;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
		this.orderDate = orderDate;
	}

	public Orders(int id, Accounts accounts, boolean status, String customerAddress, String customerEmail,
			String customerName, String customerPhone, Date orderDate, Set<OrderDetails> orderDetailses) {
		this.id = id;
		this.accounts = accounts;
		this.status = status;
		this.customerAddress = customerAddress;
		this.customerEmail = customerEmail;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
		this.orderDate = orderDate;
		this.orderDetailses = orderDetailses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId")
	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "customer_Address", nullable = false)
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	@Column(name = "customer_Email", nullable = false, length = 128)
	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	@Column(name = "customer_Name", nullable = false)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_Phone", nullable = false, length = 128)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_Date", nullable = false, length = 23)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
