package demo.entities2;
// Generated Apr 4, 2017 12:53:28 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CategoryLanguage generated by hbm2java
 */
@Entity
@Table(name = "category_language", catalog = "myProject")
public class CategoryLanguage implements java.io.Serializable {

	private CategoryLanguageId id;
	private Categories categories;
	private Languages languages;
	private Serializable name;

	public CategoryLanguage() {
	}

	public CategoryLanguage(CategoryLanguageId id, Categories categories, Languages languages, Serializable name) {
		this.id = id;
		this.categories = categories;
		this.languages = languages;
		this.name = name;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "languageId", column = @Column(name = "languageID", nullable = false, length = 10)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "categoryID", nullable = false)) })
	public CategoryLanguageId getId() {
		return this.id;
	}

	public void setId(CategoryLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryID", nullable = false, insertable = false, updatable = false)
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "languageID", nullable = false, insertable = false, updatable = false)
	public Languages getLanguages() {
		return this.languages;
	}

	public void setLanguages(Languages languages) {
		this.languages = languages;
	}

	@Column(name = "name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

}
