package demo.entities2;
// Generated Apr 9, 2017 12:19:27 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryLanguagesId generated by hbm2java
 */
@Embeddable
public class CategoryLanguagesId implements java.io.Serializable {

	private String languageId;
	private int categoryId;

	public CategoryLanguagesId() {
	}

	public CategoryLanguagesId(String languageId, int categoryId) {
		this.languageId = languageId;
		this.categoryId = categoryId;
	}

	@Column(name = "languageID", nullable = false, length = 10)
	public String getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(String languageId) {
		this.languageId = languageId;
	}

	@Column(name = "categoryID", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryLanguagesId))
			return false;
		CategoryLanguagesId castOther = (CategoryLanguagesId) other;

		return ((this.getLanguageId() == castOther.getLanguageId()) || (this.getLanguageId() != null
				&& castOther.getLanguageId() != null && this.getLanguageId().equals(castOther.getLanguageId())))
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLanguageId() == null ? 0 : this.getLanguageId().hashCode());
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
