package demo.entities2;
// Generated Apr 9, 2017 12:19:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Languages generated by hbm2java
 */
@Entity
@Table(name = "languages", catalog = "myProject")
public class Languages implements java.io.Serializable {

	private String id;
	private String name;
	private Set<ProductLanguages> productLanguageses = new HashSet<ProductLanguages>(0);
	private Set<CategoryLanguages> categoryLanguageses = new HashSet<CategoryLanguages>(0);

	public Languages() {
	}

	public Languages(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Languages(String id, String name, Set<ProductLanguages> productLanguageses,
			Set<CategoryLanguages> categoryLanguageses) {
		this.id = id;
		this.name = name;
		this.productLanguageses = productLanguageses;
		this.categoryLanguageses = categoryLanguageses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "languages")
	public Set<ProductLanguages> getProductLanguageses() {
		return this.productLanguageses;
	}

	public void setProductLanguageses(Set<ProductLanguages> productLanguageses) {
		this.productLanguageses = productLanguageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "languages")
	public Set<CategoryLanguages> getCategoryLanguageses() {
		return this.categoryLanguageses;
	}

	public void setCategoryLanguageses(Set<CategoryLanguages> categoryLanguageses) {
		this.categoryLanguageses = categoryLanguageses;
	}

}
